### ISSUE TITLE
Bamboolib stop working - Just says is loading

### ISSUE THREAD

**Issue by ManuelBanza** [tkrabel/bamboolib#19]
*Installed with pip

*bamboolib/extension  enabled 
      - Validating: OK

### Description of Issue

Bamboolib stop working. I tried to install everything again but the problem remains.

<img width="154" alt="Captura de ecrã 2020-05-12, às 17 49 35" src="https://user-images.githubusercontent.com/53525022/81722254-0390db00-9479-11ea-94b4-c46b9f0f76ff.png">

Thanks

**Comment by tkrabel** [comment]
Hi @ManuelBanza - could you run `bam.test_setup()` in your Jupyter Notebook and share the output with me?

My best guess is that some extensions didn't get installed properly.

**Comment by Satinder83** [comment]
Hi, I have a similar issue, I am using Bamboolib in Kaggle Kernel and it still says loading, I refreshed page after installing bamboolib as advised and no improvement
![image](https://user-images.githubusercontent.com/40297312/87875406-9f494500-c9ee-11ea-98cc-a7ae4d58a66c.png)
[](url)

Adding test_setup screenshot

![image](https://user-images.githubusercontent.com/40297312/87875448-e59ea400-c9ee-11ea-8e01-b99755ccb7ac.png)

**Comment by FlorianWetschoreck** [comment]
Thank you for reporting this issue and we are sorry for the inconvenience. It seems like Kaggle changed the way how they allow Notebook extensions. This seems to have broken the support both for qgrid but also for bamboolib.

We reached out to Kaggle in order to white-list the extensions and we will report back once there is some decision or progress.

In the meantime, you can continue using bamboolib in binder notebooks or on your local laptop via a trial. I hope that those are some options for you.

Best,
Florian

**Comment by tkrabel** [comment]
bamboolib is free on local Notebooks now. Kaggle support is still pending (we're waiting for their reply). Sorry about that ....

**Comment by JJ-BO** [comment]
stil not working. i am using anaconda. and same issue on jupyter lab
