### ISSUE TITLE
bamboolib continued development

### ISSUE THREAD

**Issue by hanifa2102** [tkrabel/bamboolib#50]
Hi, 
    seems bamboolib hasnt seen development since python 3.8. Any plans to continue development to the latest python versions like 3.11 etc ?
From a bamboolib fan.

**Comment by tkrabel** [comment]
Hey @hanifa2102 - thanks for reaching out. Since the [Databricks acquisition of 8080 Labs](https://www.databricks.com/company/newsroom/press-releases/databricks-acquires-low-code-no-code-company-to-expand-its-lakehouse-platform-to-citizen-data-scientists), bamboolib has been released in an uncompiled version, which should make it compatible with later python versions.

That said, there are no further investments into bamboolib at this point :/

**Comment by hanifa2102** [comment]
Hi @tkrabel , when you mean uncompiled version, is it like some exe which we can download ? Or is it only strictly part of the Databricks ecosystem ?

**Comment by tkrabel** [comment]
You can simply pip install the latest version of the library and will have all the source code. Alternatively, you can download the code from pypi.org.

**Comment by hanifa2102** [comment]
@tkrabel 
Thanks,  got it and wish the team all the best as well.
